/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "SprayZ"


pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
    }
}