name: ${pluginName}
version: ${version}
main: de.crazj.sprayz.SprayZ
loader: de.crazj.sprayz.DependencyLoader
api-version: ${minecraftGen}
author: crazj_
description: A plugin that adds sprays like in other games
dependencies:
  bootstrap:
    DependencyLoader:
      load: BEFORE
      required: true
  server:
    KSpigot:
      load: BEFORE
      required: false
      join-classpath: true
    NBTAPI:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  sprayz.use:
    description: Allows you to use the SprayZ plugin
    default: op